config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root   'tweets#index'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tweet_tags, dependent: :destroy
    has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :tweet_tags, dependent: :destroy
    has_many :tags, through: :tweet_tags
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  validates :car_lovers, presence: true

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        # サインアップ時にnameのストロングパラメータを追加
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :car_lovers])
        # アカウント編集の時にnameとprofileのストロングパラメータを追加
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      tweet = Tweet.find(params[:tweet_id])
      comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
def index
end

def link
end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
      redirect_back(fallback_location: root_path)
    end
  
    def destroy
      like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
    def index
      if params[:search] == nil
        @tweets = params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets : Tweet.all
      elsif params[:search] == ''
        @tweets = params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets : Tweet.all
      else
        #部分検索
        @tweets = Tweet.where("body LIKE ? ",'%' + params[:search] + '%')
      end
    end

    def new
        @tweet = Tweet.new
    end

    def create
        tweet = Tweet.new(tweet_params)

        tweet.user_id = current_user.id
        
        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
      @tweet = Tweet.find(params[:id])
      @comments = @tweet.comments
      @comment = Comment.new
    end

    def edit
      @tweet = Tweet.find(params[:id])
    end

    def update
      tweet = Tweet.find(params[:id])
      if tweet.update(tweet_params)
        redirect_to :action => "show", :id => tweet.id
      else
        redirect_to :action => "new"
      end
    end

    def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
      redirect_to action: :index
    end

     private
     def tweet_params
        params.require(:tweet).permit(:body, :image, :title, tag_ids: [])
     end
     

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hello/link.html.erb
My name is GeekSalon.
<%= link_to 'トップページ', hello_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geektwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  </head>

  <body>
   <header>
      <h1>GeekTwitter</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", tweets_path %></li>
        <li><%= link_to "新規投稿",new_tweet_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>

      </ul>
      </div>
    </header>
    <main>
     <%= yield %>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    </main>
    <footer>
     <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<section id="second-block">
  <div class="about-container">
      <p class="info-text">
        <b>-サイトのコンセプト-</b>
        <br>
        <span class="font-small">
        このサイトは車好きと最近車に興味が出た人をつなげる交流の場です
        <br>
        気になった車の話題について語り合うことができます
        <br>
        ユーザーは車好き
        </span>
      </p>  </section>
  </div>

<section id="third-block">
    <h2>Tweet一覧</h2>
    <hr>

    <h3>投稿を検索</h3>
        <%= form_tag tweets_path, method: :get, class: 'boards__searchForm' do %>
          <%= select_tag :tag_id,
                        options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                        {
                          prompt: 'タグで絞り込み検索',
                            onchange: 'submit(this.form);'
                        }
          %>
      <% end %>



    <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索する'  %>
      <% end %>



    <div class="tweets-container">
      <% @tweets.each do |t| %>

      <div class="tweet"> 
          <%= t.user.car_lovers %>
          
        <%= image_tag t.image_url, size: "250x200" if t.image? %>
        <%= t.body %>

        

        <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
                <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
            <% else %>
                <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
            <% end %>
        <% else %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>

        <div class="left-container"><%= t.body %></div>

        <%= t.created_at %>

        <%= link_to "詳細へ", tweet_path(t.id) %>
        
        <div class="bottom-item">
          <a href="/tweets/<%= t.id %>"><i class="fa fa-comment regular"></i></a>
        </div>
        <% if user_signed_in? && current_user.id == t.user_id %>
            <%= link_to "編集する", edit_tweet_path(t.id) %>
            <%= button_to "削除する", tweet_path(t.id), method: :delete %>
        <% end %>
      </div>

        

            <p class="time"><%= t.created_at %></p>
        
      

      

        <% t.tags.each do |tag| %>
          <%= tag.name %>
        <% end %>
      <% end %>
    </div>

</div>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'newtweet', :media => "all" %>


<div class="wrapper">
  <h1>新規Tweet</h1>
</div>

<div class="wrapper2">
    <div class="index-tweet">
    <%= form_for @tweet do |f| %>

      <div class="wrapper1">
        <h2>タイトル</h2>
      </div>
      <div class="field1">
        <%= f.text_field :title, :size => 140 %>
      </div>
      
      <div class="wrapper1">
        <h2>ツイート内容</h2>
      </div>
      <div class="field1">
        <%= f.text_field :body, :size => 140 %>
      </div>

      <div class="check_box">
        <span>タグ</span>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
        <div>
          <%= tag.label do %>
            <%= tag.check_box %>
            <%= tag.text %>
          <% end %>
        </div>
      <% end %>
      </div>


      <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>

    

      <%= f.submit "Tweetする" %>
    <% end %>
    <%= link_to "Tweet一覧に戻る", tweets_path %>


    </div>

</div>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.user.email %></p>
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>

  <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
          <%= link_to tweet_like_path(@tweet), method: :delete do %>
            <i class="fas fa-heart"></i><%= @tweet.likes.count %>
          <% end %>
      <% else %>
          <%= link_to tweet_likes_path(@tweet), method: :post do %>
            <i class="fas fa-heart"></i><%= @tweet.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="fas fa-heart"></i><%= @tweet.likes.count %>
  <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

<% @tweet.tags.each do |tag| %>
  <%= tag.name %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>